TOTAL_TIME = "tottime"
DESCRIPTOR = "filename:lineno(function)"
NCALL_IDX = 0
PERCALL_IDX = 2

BARCHART_FILE_OUTPUT = 'barchart.html'
TABLE_FILE_OUTPUT = 'table.html'
LINECHART_FILE_OUTPUT = 'linechart.html'
AREACHART_FILE_OUTPUT = 'areachart.html'
STACKEDBARCHART_FILE_OUTPUT = 'stackedbarchart.html'
BUBBLECHART_FILE_OUTPUT = 'bubblechart.html'

HORIZONTAL_BAR_CHART = "bar"
STACKED_BAR_CHART = "stacked"
TABLE = "table"
LINE_CHART = "line"
AREA_CHART = "area"
BUBBLE_CHART = "bubble"
CHART_TYPES = {HORIZONTAL_BAR_CHART, TABLE, LINE_CHART, AREA_CHART, STACKED_BAR_CHART, BUBBLE_CHART}

HORIZONTAL_ORIENTATION = 'h'
TIME_PERCENTAGE_LABEL = 'TIME %'