TOTAL_TIME = "tottime"
DESCRIPTOR = "filename:lineno(function)"

BARCHART_FILE_OUTPUT = 'barchart.html'
TABLE_FILE_OUTPUT = 'table.html'

HORIZONTAL_BAR_CHART = "bar"
TABLE = "table"
CHART_TYPES = {HORIZONTAL_BAR_CHART, TABLE}

HORIZONTAL_ORIENTATION = 'h'
TIME_PERCENTAGE_LABEL = 'TIME %'