TOTAL_TIME = "tottime"
DESCRIPTOR = "filename:lineno(function)"

BARCHART_FILE_OUTPUT = 'barchart.html'
TABLE_FILE_OUTPUT = 'table.html'
LINECHART_FILE_OUTPUT = 'linechart.html'

HORIZONTAL_BAR_CHART = "bar"
TABLE = "table"
LINE_CHART = "line"
CHART_TYPES = {HORIZONTAL_BAR_CHART, TABLE, LINE_CHART}

HORIZONTAL_ORIENTATION = 'h'
TIME_PERCENTAGE_LABEL = 'TIME %'